// Maps world-atlas numeric ISO codes (without leading zeros) to name + alpha-2
// Used by the geocoder and for flag emoji generation
export const COUNTRY_DATA: Record<string, { name: string; alpha2: string }> = {
  // Africa
  "12": { name: "Algeria", alpha2: "DZ" },
  "24": { name: "Angola", alpha2: "AO" },
  "204": { name: "Benin", alpha2: "BJ" },
  "72": { name: "Botswana", alpha2: "BW" },
  "854": { name: "Burkina Faso", alpha2: "BF" },
  "108": { name: "Burundi", alpha2: "BI" },
  "120": { name: "Cameroon", alpha2: "CM" },
  "132": { name: "Cape Verde", alpha2: "CV" },
  "140": { name: "Central African Republic", alpha2: "CF" },
  "148": { name: "Chad", alpha2: "TD" },
  "174": { name: "Comoros", alpha2: "KM" },
  "178": { name: "Republic of Congo", alpha2: "CG" },
  "180": { name: "DR Congo", alpha2: "CD" },
  "262": { name: "Djibouti", alpha2: "DJ" },
  "818": { name: "Egypt", alpha2: "EG" },
  "226": { name: "Equatorial Guinea", alpha2: "GQ" },
  "232": { name: "Eritrea", alpha2: "ER" },
  "748": { name: "Eswatini", alpha2: "SZ" },
  "231": { name: "Ethiopia", alpha2: "ET" },
  "266": { name: "Gabon", alpha2: "GA" },
  "270": { name: "Gambia", alpha2: "GM" },
  "288": { name: "Ghana", alpha2: "GH" },
  "324": { name: "Guinea", alpha2: "GN" },
  "624": { name: "Guinea-Bissau", alpha2: "GW" },
  "384": { name: "Ivory Coast", alpha2: "CI" },
  "404": { name: "Kenya", alpha2: "KE" },
  "426": { name: "Lesotho", alpha2: "LS" },
  "430": { name: "Liberia", alpha2: "LR" },
  "434": { name: "Libya", alpha2: "LY" },
  "450": { name: "Madagascar", alpha2: "MG" },
  "454": { name: "Malawi", alpha2: "MW" },
  "466": { name: "Mali", alpha2: "ML" },
  "478": { name: "Mauritania", alpha2: "MR" },
  "504": { name: "Morocco", alpha2: "MA" },
  "508": { name: "Mozambique", alpha2: "MZ" },
  "516": { name: "Namibia", alpha2: "NA" },
  "562": { name: "Niger", alpha2: "NE" },
  "566": { name: "Nigeria", alpha2: "NG" },
  "646": { name: "Rwanda", alpha2: "RW" },
  "678": { name: "São Tomé and Príncipe", alpha2: "ST" },
  "686": { name: "Senegal", alpha2: "SN" },
  "694": { name: "Sierra Leone", alpha2: "SL" },
  "706": { name: "Somalia", alpha2: "SO" },
  "710": { name: "South Africa", alpha2: "ZA" },
  "728": { name: "South Sudan", alpha2: "SS" },
  "729": { name: "Sudan", alpha2: "SD" },
  "834": { name: "Tanzania", alpha2: "TZ" },
  "768": { name: "Togo", alpha2: "TG" },
  "788": { name: "Tunisia", alpha2: "TN" },
  "800": { name: "Uganda", alpha2: "UG" },
  "894": { name: "Zambia", alpha2: "ZM" },
  "716": { name: "Zimbabwe", alpha2: "ZW" },

  // Americas
  "32": { name: "Argentina", alpha2: "AR" },
  "44": { name: "Bahamas", alpha2: "BS" },
  "52": { name: "Barbados", alpha2: "BB" },
  "84": { name: "Belize", alpha2: "BZ" },
  "68": { name: "Bolivia", alpha2: "BO" },
  "76": { name: "Brazil", alpha2: "BR" },
  "124": { name: "Canada", alpha2: "CA" },
  "152": { name: "Chile", alpha2: "CL" },
  "170": { name: "Colombia", alpha2: "CO" },
  "188": { name: "Costa Rica", alpha2: "CR" },
  "192": { name: "Cuba", alpha2: "CU" },
  "214": { name: "Dominican Republic", alpha2: "DO" },
  "218": { name: "Ecuador", alpha2: "EC" },
  "222": { name: "El Salvador", alpha2: "SV" },
  "320": { name: "Guatemala", alpha2: "GT" },
  "328": { name: "Guyana", alpha2: "GY" },
  "332": { name: "Haiti", alpha2: "HT" },
  "340": { name: "Honduras", alpha2: "HN" },
  "388": { name: "Jamaica", alpha2: "JM" },
  "484": { name: "Mexico", alpha2: "MX" },
  "558": { name: "Nicaragua", alpha2: "NI" },
  "591": { name: "Panama", alpha2: "PA" },
  "600": { name: "Paraguay", alpha2: "PY" },
  "604": { name: "Peru", alpha2: "PE" },
  "740": { name: "Suriname", alpha2: "SR" },
  "780": { name: "Trinidad and Tobago", alpha2: "TT" },
  "840": { name: "United States", alpha2: "US" },
  "858": { name: "Uruguay", alpha2: "UY" },
  "862": { name: "Venezuela", alpha2: "VE" },

  // Asia
  "4": { name: "Afghanistan", alpha2: "AF" },
  "50": { name: "Bangladesh", alpha2: "BD" },
  "64": { name: "Bhutan", alpha2: "BT" },
  "96": { name: "Brunei", alpha2: "BN" },
  "116": { name: "Cambodia", alpha2: "KH" },
  "156": { name: "China", alpha2: "CN" },
  "356": { name: "India", alpha2: "IN" },
  "360": { name: "Indonesia", alpha2: "ID" },
  "364": { name: "Iran", alpha2: "IR" },
  "368": { name: "Iraq", alpha2: "IQ" },
  "376": { name: "Israel", alpha2: "IL" },
  "392": { name: "Japan", alpha2: "JP" },
  "400": { name: "Jordan", alpha2: "JO" },
  "398": { name: "Kazakhstan", alpha2: "KZ" },
  "408": { name: "North Korea", alpha2: "KP" },
  "410": { name: "South Korea", alpha2: "KR" },
  "414": { name: "Kuwait", alpha2: "KW" },
  "417": { name: "Kyrgyzstan", alpha2: "KG" },
  "418": { name: "Laos", alpha2: "LA" },
  "422": { name: "Lebanon", alpha2: "LB" },
  "458": { name: "Malaysia", alpha2: "MY" },
  "496": { name: "Mongolia", alpha2: "MN" },
  "104": { name: "Myanmar", alpha2: "MM" },
  "524": { name: "Nepal", alpha2: "NP" },
  "512": { name: "Oman", alpha2: "OM" },
  "586": { name: "Pakistan", alpha2: "PK" },
  "608": { name: "Philippines", alpha2: "PH" },
  "634": { name: "Qatar", alpha2: "QA" },
  "682": { name: "Saudi Arabia", alpha2: "SA" },
  "702": { name: "Singapore", alpha2: "SG" },
  "144": { name: "Sri Lanka", alpha2: "LK" },
  "760": { name: "Syria", alpha2: "SY" },
  "158": { name: "Taiwan", alpha2: "TW" },
  "762": { name: "Tajikistan", alpha2: "TJ" },
  "764": { name: "Thailand", alpha2: "TH" },
  "626": { name: "Timor-Leste", alpha2: "TL" },
  "792": { name: "Turkey", alpha2: "TR" },
  "795": { name: "Turkmenistan", alpha2: "TM" },
  "784": { name: "United Arab Emirates", alpha2: "AE" },
  "860": { name: "Uzbekistan", alpha2: "UZ" },
  "704": { name: "Vietnam", alpha2: "VN" },
  "887": { name: "Yemen", alpha2: "YE" },

  // Europe
  "8": { name: "Albania", alpha2: "AL" },
  "20": { name: "Andorra", alpha2: "AD" },
  "40": { name: "Austria", alpha2: "AT" },
  "112": { name: "Belarus", alpha2: "BY" },
  "56": { name: "Belgium", alpha2: "BE" },
  "70": { name: "Bosnia and Herzegovina", alpha2: "BA" },
  "100": { name: "Bulgaria", alpha2: "BG" },
  "191": { name: "Croatia", alpha2: "HR" },
  "196": { name: "Cyprus", alpha2: "CY" },
  "203": { name: "Czechia", alpha2: "CZ" },
  "208": { name: "Denmark", alpha2: "DK" },
  "233": { name: "Estonia", alpha2: "EE" },
  "246": { name: "Finland", alpha2: "FI" },
  "250": { name: "France", alpha2: "FR" },
  "268": { name: "Georgia", alpha2: "GE" },
  "276": { name: "Germany", alpha2: "DE" },
  "300": { name: "Greece", alpha2: "GR" },
  "348": { name: "Hungary", alpha2: "HU" },
  "352": { name: "Iceland", alpha2: "IS" },
  "372": { name: "Ireland", alpha2: "IE" },
  "380": { name: "Italy", alpha2: "IT" },
  "428": { name: "Latvia", alpha2: "LV" },
  "438": { name: "Liechtenstein", alpha2: "LI" },
  "440": { name: "Lithuania", alpha2: "LT" },
  "442": { name: "Luxembourg", alpha2: "LU" },
  "470": { name: "Malta", alpha2: "MT" },
  "498": { name: "Moldova", alpha2: "MD" },
  "492": { name: "Monaco", alpha2: "MC" },
  "499": { name: "Montenegro", alpha2: "ME" },
  "528": { name: "Netherlands", alpha2: "NL" },
  "807": { name: "North Macedonia", alpha2: "MK" },
  "578": { name: "Norway", alpha2: "NO" },
  "616": { name: "Poland", alpha2: "PL" },
  "620": { name: "Portugal", alpha2: "PT" },
  "642": { name: "Romania", alpha2: "RO" },
  "643": { name: "Russia", alpha2: "RU" },
  "674": { name: "San Marino", alpha2: "SM" },
  "688": { name: "Serbia", alpha2: "RS" },
  "703": { name: "Slovakia", alpha2: "SK" },
  "705": { name: "Slovenia", alpha2: "SI" },
  "724": { name: "Spain", alpha2: "ES" },
  "752": { name: "Sweden", alpha2: "SE" },
  "756": { name: "Switzerland", alpha2: "CH" },
  "804": { name: "Ukraine", alpha2: "UA" },
  "826": { name: "United Kingdom", alpha2: "GB" },

  // Oceania
  "36": { name: "Australia", alpha2: "AU" },
  "242": { name: "Fiji", alpha2: "FJ" },
  "296": { name: "Kiribati", alpha2: "KI" },
  "584": { name: "Marshall Islands", alpha2: "MH" },
  "583": { name: "Micronesia", alpha2: "FM" },
  "520": { name: "Nauru", alpha2: "NR" },
  "554": { name: "New Zealand", alpha2: "NZ" },
  "585": { name: "Palau", alpha2: "PW" },
  "598": { name: "Papua New Guinea", alpha2: "PG" },
  "882": { name: "Samoa", alpha2: "WS" },
  "90": { name: "Solomon Islands", alpha2: "SB" },
  "776": { name: "Tonga", alpha2: "TO" },
  "798": { name: "Tuvalu", alpha2: "TV" },
  "548": { name: "Vanuatu", alpha2: "VU" },
}

export function getFlag(alpha2: string): string {
  return alpha2
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('')
}

export const TOTAL_COUNTRIES_IN_WORLD = 195
